import { useId } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import type { QrSlot as QrSlotType } from '../state';
import { QR_BASE_SIZE } from '../state';
import { useSvgDrag } from './useSvgDrag';

type Props = {
  slot: QrSlotType;
  onMove: (x: number, y: number) => void;
};

// QR code slot. Generated by qrcode.react as a native <svg> which nests
// inside our preview SVG. Transform is applied around the slot's center.
//
// When `includeAvatar` is on, we render the avatar manually (rather than
// using qrcode.react's imageSettings) so we can:
//   1. Make the visible avatar smaller than the outer "slot" circle, giving
//      the face clearance from the borders rather than being eaten by them.
//   2. Clip the (square) avatar.jpg to a perfect circle.
// Level "H" gives ~30% error-correction; we mask ~6% of the QR area, so it
// remains comfortably scannable without explicit excavation.
export function QrCode({ slot, onMove }: Props) {
  const uid = useId().replace(/:/g, '');
  const clipId = `qr-avatar-clip-${uid}`;
  const drag = useSvgDrag({ x: slot.x, y: slot.y, onMove });

  if (!slot.enabled) return null;

  const size = QR_BASE_SIZE;
  // Outer slot (incl. pink + white border ring). Same diameter as before.
  const slotOuterRadius = (size * 0.28) / 2;
  // Visible avatar — smaller, so face sits comfortably inside the borders.
  const avatarVisibleRadius = (size * 0.20) / 2;
  const avatarBorderWidth = 5;

  const cx = size / 2;
  const cy = size / 2;

  const transform = `translate(${slot.x} ${slot.y}) rotate(${slot.rotation}) scale(${slot.scale})`;

  return (
    <g
      transform={transform}
      {...drag.handlers}
      style={{ cursor: drag.isDragging ? 'grabbing' : 'grab', touchAction: 'none' }}
    >
      {/* Nested <svg> with x/y offset of -size/2 so the QR is centered on
          (0,0) before the outer transform applies. */}
      <svg x={-size / 2} y={-size / 2} width={size} height={size} overflow="visible">
        <QRCodeSVG
          value={slot.url || ' '}
          size={size}
          level="H"
          marginSize={2}
          bgColor="#ffffff"
          fgColor="#000000"
        />
        {slot.includeAvatar && (
          <>
            <defs>
              <clipPath id={clipId}>
                <circle cx={cx} cy={cy} r={avatarVisibleRadius} />
              </clipPath>
            </defs>
            {/* White disc masks the QR modules behind the avatar slot. */}
            <circle cx={cx} cy={cy} r={slotOuterRadius} fill="#ffffff" />
            {/* Avatar image clipped to a smaller circle so the face has
                white breathing room before the borders begin. */}
            <image
              href="/static/images/avatar.jpg"
              x={cx - avatarVisibleRadius}
              y={cy - avatarVisibleRadius}
              width={avatarVisibleRadius * 2}
              height={avatarVisibleRadius * 2}
              preserveAspectRatio="xMidYMid slice"
              clipPath={`url(#${clipId})`}
            />
            {/* Pink border ring. */}
            <circle
              cx={cx}
              cy={cy}
              r={slotOuterRadius - avatarBorderWidth / 2}
              fill="none"
              stroke="#ff7369"
              strokeWidth={avatarBorderWidth}
            />
            {/* 1px white line just inside the pink border. */}
            <circle
              cx={cx}
              cy={cy}
              r={slotOuterRadius - avatarBorderWidth - 0.5}
              fill="none"
              stroke="#ffffff"
              strokeWidth={1}
            />
          </>
        )}
      </svg>
    </g>
  );
}
